name: Android Build and Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29  # Atau sesuaikan dengan versi API yang kamu inginkan 
          build-tools: 29.0.2  # Atau sesuaikan dengan build tools yang kamu butuhkan

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew  # Memberikan izin eksekusi pada file gradlew

      - name: Gradle build APK
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/debug/arrahman-dev-v1.apk

      - name: Upload APK to server via API
        run: |
          curl -X POST -F "apk_file=@app/build/outputs/apk/debug/arrahman-dev-v1.apk" \
               -H "Content-Type: multipart/form-data" \
               https://aplikasi.cizypos.com/Upload/upload_apk
