name: Android Build and Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        api-level: [28, 29, 30]
        build-tools: [27.0.3, 29.0.2, 30.0.3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
        
      - name: Set up Android SDK
        uses: reactivecircus/android-setup-action@v2
        with:
          api-level: ${{ matrix.api-level }}
          build-tools: ${{ matrix.build-tools }}

      - name: Gradle build APK
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/arrahman-dev-v1.apk

      - name: Upload APK to server via API
        run: |
          curl -X POST -F "apk_file=@app/build/outputs/apk/release/arrahman-dev-v1.apk" \
               -H "Content-Type: multipart/form-data" \
               http://your-server.com/index.php/uploadcontroller/upload_apk
